[package]
name = "raft"
version = "0.7.0"
authors = ["The TiKV Project Developers"]
license = "Apache-2.0"
keywords = ["raft", "distributed-systems", "ha"]
description = "Vendored raft crate with prost 0.12 compatibility"
edition = "2021"

# Keep out of workspace - used via [patch]
[workspace]

[features]
default = ["prost-codec", "default-logger"]
failpoints = ["fail/failpoints"]
prost-codec = ["raft-proto/prost-codec"]
default-logger = ["slog-stdlog", "slog-envlogger", "slog-term"]

[dependencies]
bytes = "1"
fxhash = "0.2.1"
fail = { version = "0.5", optional = true }
getset = "0.1.1"
prost = "0.12"
thiserror = "1.0"
raft-proto = { path = "../raft-proto", version = "0.7.0", default-features = false }
rand = "0.8"
slog = "2.2"
slog-envlogger = { version = "2.1.0", optional = true }
slog-stdlog = { version = "4", optional = true }
slog-term = { version = "2.4.0", optional = true }

[dev-dependencies]
regex = "1"
slog-async = "2.3.0"
slog-envlogger = "2.1.0"
slog-stdlog = "4"
slog-term = "2.4.0"
anyhow = "1.0"
itertools = "0.10.0"
